"""Clause language for relational rule induction.

A clause is:
  SELECT targets WHERE target_predicates
  FOR EACH target:
    FIND support WHERE support_predicates(support, target)
    DERIVE attributes FROM aggregations(support)
    APPLY action(target, attributes)

The inducer discovers clauses from demo pairs.
The executor applies clauses to build output.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable
from enum import Enum, auto

import numpy as np

from aria.guided.perceive import perceive, GridFacts, ObjFact
from aria.types import Grid


# ---------------------------------------------------------------------------
# Predicates: conditions on objects
# ---------------------------------------------------------------------------

class Pred(Enum):
    """Atomic predicates over objects.

    Only includes predicates that are actually executable by Predicate.test()
    and generated by the inducer.
    """
    # Size predicates
    IS_SMALLEST = auto()
    IS_LARGEST = auto()
    SIZE_EQ = auto()           # param: size
    SIZE_LT = auto()           # param: threshold
    SIZE_GT = auto()           # param: threshold
    IS_SINGLETON = auto()      # size == 1

    # Color predicates
    COLOR_EQ = auto()          # param: color
    UNIQUE_COLOR = auto()      # only object with this color

    # Shape predicates
    IS_RECTANGULAR = auto()
    IS_LINE = auto()
    IS_SQUARE = auto()

    # Position predicates
    TOUCHES_BORDER = auto()
    NOT_TOUCHES_BORDER = auto()

    # Relational predicates — param: (relation, other_predicate)
    # Tests whether ANY other object satisfying other_predicate has
    # the specified spatial relation to this object.
    ADJACENT_TO = auto()       # param: Predicate (the other object's selector)
    CONTAINED_BY = auto()      # param: Predicate
    CONTAINS = auto()          # param: Predicate
    SAME_SHAPE_AS = auto()     # param: Predicate

    # Combinator
    NOT = auto()               # param: Predicate — negation


@dataclass(frozen=True)
class Predicate:
    pred: Pred
    param: Any = None

    def test(self, obj: ObjFact, all_objs: list[ObjFact], pairs: list = None) -> bool:
        if self.pred == Pred.IS_SMALLEST:
            return obj.size == min(o.size for o in all_objs)
        if self.pred == Pred.IS_LARGEST:
            return obj.size == max(o.size for o in all_objs)
        if self.pred == Pred.SIZE_EQ:
            return obj.size == self.param
        if self.pred == Pred.SIZE_LT:
            return obj.size < self.param
        if self.pred == Pred.SIZE_GT:
            return obj.size > self.param
        if self.pred == Pred.IS_SINGLETON:
            return obj.size == 1
        if self.pred == Pred.COLOR_EQ:
            return obj.color == self.param
        if self.pred == Pred.UNIQUE_COLOR:
            return obj.n_same_color == 1
        if self.pred == Pred.IS_RECTANGULAR:
            return obj.is_rectangular
        if self.pred == Pred.IS_LINE:
            return obj.is_line
        if self.pred == Pred.IS_SQUARE:
            return obj.is_square
        if self.pred == Pred.TOUCHES_BORDER:
            return obj.touches_top or obj.touches_bottom or obj.touches_left or obj.touches_right
        if self.pred == Pred.NOT_TOUCHES_BORDER:
            return not (obj.touches_top or obj.touches_bottom or obj.touches_left or obj.touches_right)

        # NOT combinator
        if self.pred == Pred.NOT:
            inner = self.param  # a Predicate
            return not inner.test(obj, all_objs, pairs)

        # Relational predicates — check if ANY other object satisfying
        # self.param has the specified relation to obj
        if self.pred in (Pred.ADJACENT_TO, Pred.CONTAINED_BY,
                         Pred.CONTAINS, Pred.SAME_SHAPE_AS):
            other_pred = self.param  # a Predicate
            if pairs is None:
                return False
            for other in all_objs:
                if other.oid == obj.oid:
                    continue
                if not other_pred.test(other, all_objs, pairs):
                    continue
                # Check the specific relation
                if self.pred == Pred.ADJACENT_TO:
                    if _are_adjacent(obj, other):
                        return True
                elif self.pred == Pred.CONTAINED_BY:
                    if _is_contained(obj, other):
                        return True
                elif self.pred == Pred.CONTAINS:
                    if _is_contained(other, obj):
                        return True
                elif self.pred == Pred.SAME_SHAPE_AS:
                    if (obj.height == other.height and obj.width == other.width
                            and np.array_equal(obj.mask, other.mask)):
                        return True
            return False

        return False


# ---------------------------------------------------------------------------
# Aggregations: derive attributes from support set
# ---------------------------------------------------------------------------

class Agg(Enum):
    """How to derive an attribute from support objects."""
    COLOR_OF = auto()          # take the color
    SIZE_OF = auto()
    ROW_OF = auto()
    COL_OF = auto()
    SHAPE_OF = auto()          # take the mask
    COUNT = auto()             # number of support objects
    MOST_COMMON_COLOR = auto() # most frequent color in a region
    FRAME_COLOR = auto()       # most common non-bg color adjacent to enclosed bg
    LEARNED_MAP = auto()       # value from a demo-learned lookup table


# ---------------------------------------------------------------------------
# Actions: what to do with the target
# ---------------------------------------------------------------------------

class Act(Enum):
    """What to write for the target object."""
    RECOLOR = auto()           # change color to derived value
    PLACE = auto()             # place at same position with derived color
    PLACE_AT = auto()          # place at derived position
    REMOVE = auto()            # don't include in output
    KEEP = auto()              # keep as-is from input
    PLACE_PIXEL = auto()       # place single pixel at specific position
    FILL_ENCLOSED = auto()     # fill enclosed bg regions with derived color
    STAMP = auto()             # copy target mask at offset; target is PRESERVED
    GRAVITY = auto()           # project target along axis to grid border
    SLIDE = auto()             # slide target along axis until hitting non-bg
    TRANSFORM = auto()         # geometric transform: flip_h, flip_v, rot90, rot180
    FILL_INTERIOR = auto()     # fill bg holes within target's bbox with derived color


# ---------------------------------------------------------------------------
# Clause: one complete rule
# ---------------------------------------------------------------------------

@dataclass
class Clause:
    """A complete relational rule.

    Reads as:
      SELECT targets WHERE target_preds
      FIND support WHERE support_preds(support, target)
      DERIVE attribute via aggregation
      APPLY action using attribute
    """
    # Target selection
    target_preds: list[Predicate]

    # Support selection (relative to target)
    support_preds: list[Predicate]

    # Derivation
    aggregation: Agg

    # Action
    action: Act

    # Description (for debugging)
    description: str = ""

    def select_targets(self, facts: GridFacts) -> list[ObjFact]:
        if not self.target_preds:
            return []  # no predicates = no object targets (region-based rule)
        return [o for o in facts.objects
                if all(p.test(o, facts.objects) for p in self.target_preds)]

    def find_support(self, target: ObjFact, facts: GridFacts) -> list[ObjFact]:
        return [o for o in facts.objects
                if o.oid != target.oid and
                all(p.test(o, facts.objects) for p in self.support_preds)]

    def derive(self, support: list[ObjFact], facts: GridFacts = None,
               grid: np.ndarray = None) -> Any:
        if self.aggregation == Agg.MOST_COMMON_COLOR and facts is not None:
            data_regions = [r for r in facts.regions if r.role == "data"]
            if data_regions:
                sep_colors = {s.color for s in facts.separators}
                counts = {k: v for k, v in data_regions[0].pixel_color_counts.items()
                          if k not in sep_colors}
                if counts:
                    return max(counts, key=counts.get)
            return None

        if self.aggregation == Agg.FRAME_COLOR and grid is not None and facts is not None:
            return _compute_frame_colors(grid, facts.bg)

        if self.aggregation == Agg.LEARNED_MAP:
            # Look up value from a demo-learned mapping.
            # Key type determined by _learned_key_type attribute.
            learned = getattr(self, '_learned_map', None)
            key_type = getattr(self, '_learned_key_type', 'shape')
            if not learned:
                return None
            if key_type == 'shape' and support:
                s = support[0]
                key = (s.height, s.width, s.mask.tobytes())
                return learned.get(key)
            if key_type == 'color':
                # Key is the target object's own color (for per-object recolor)
                # Target is passed via _current_target during execution
                ct = getattr(self, '_current_target', None)
                if ct is not None:
                    return learned.get(ct.color)
            return None

        if not support:
            return None
        s = support[0]
        if self.aggregation == Agg.COLOR_OF:
            return s.color
        if self.aggregation == Agg.SIZE_OF:
            return s.size
        if self.aggregation == Agg.ROW_OF:
            return s.row
        if self.aggregation == Agg.COL_OF:
            return s.col
        if self.aggregation == Agg.SHAPE_OF:
            return s.mask
        if self.aggregation == Agg.COUNT:
            return len(support)
        return None


# ---------------------------------------------------------------------------
# Program: ordered list of clauses applied to build output
# ---------------------------------------------------------------------------

@dataclass
class ClauseProgram:
    """A complete program: ordered clauses applied to build output."""
    clauses: list[Clause]
    output_bg: int = 0
    size_rule: Any = None  # optional SizeRule from output_size module

    def execute(self, inp: Grid, facts: GridFacts = None) -> Grid:
        if facts is None:
            facts = perceive(inp)
        bg = facts.bg
        if self.size_rule is not None:
            out_h, out_w = self.size_rule.predict(facts)
        else:
            out_h, out_w = facts.rows, facts.cols
        result = np.full((out_h, out_w), bg, dtype=np.uint8)

        # First pass: KEEP all objects not targeted by any clause
        # STAMP preserves its target, so don't mark those as targeted
        targeted_oids = set()
        for clause in self.clauses:
            if clause.action in (Act.STAMP, Act.FILL_INTERIOR):
                continue  # these actions preserve their target
            for t in clause.select_targets(facts):
                targeted_oids.add(t.oid)

        # Place non-targeted objects as-is (preserved)
        for obj in facts.objects:
            if obj.oid not in targeted_oids:
                for r in range(obj.height):
                    for c in range(obj.width):
                        if obj.mask[r, c]:
                            result[obj.row + r, obj.col + c] = obj.color

        # Second pass: apply clauses
        for clause in self.clauses:
            targets = clause.select_targets(facts)

            # Region-level actions (no target objects needed)
            if not targets and clause.action == Act.PLACE_PIXEL:
                attr = clause.derive([], facts)
                if attr is not None:
                    answer_regions = [r for r in facts.regions if r.role == "answer"]
                    if answer_regions:
                        ar = answer_regions[0]
                        if 0 <= ar.r1 < result.shape[0] and 0 <= ar.center_col < result.shape[1]:
                            result[ar.r1, ar.center_col] = attr
                continue

            # Grid-level: fill enclosed bg regions
            if not targets and clause.action == Act.FILL_ENCLOSED:
                if clause.aggregation == Agg.FRAME_COLOR:
                    # Per-region color from adjacent frame
                    frame_colors = clause.derive([], facts, grid=inp)
                    if frame_colors:
                        for (region_mask, color) in frame_colors:
                            result[region_mask] = color
                else:
                    # Single color for all enclosed regions
                    fill_color = getattr(clause, '_fill_color', None)
                    if fill_color is None:
                        # Derive from support
                        support = clause.find_support(
                            facts.objects[0] if facts.objects else None, facts)
                        fill_color = clause.derive(support, facts)
                    if fill_color is not None:
                        enclosed = _find_enclosed_bg(inp, facts.bg)
                        if enclosed is not None:
                            result[enclosed] = fill_color
                continue

            for target in targets:
                support = clause.find_support(target, facts)
                # Set current target for LEARNED_MAP color-key lookup
                clause._current_target = target
                attr = clause.derive(support, facts)
                # Constant color override (for novel colors not in input)
                if attr is None:
                    attr = getattr(clause, '_fill_color', None)

                if clause.action == Act.RECOLOR and attr is not None:
                    for r in range(target.height):
                        for c in range(target.width):
                            if target.mask[r, c]:
                                result[target.row + r, target.col + c] = attr

                elif clause.action == Act.PLACE and attr is not None:
                    for r in range(target.height):
                        for c in range(target.width):
                            if target.mask[r, c]:
                                result[target.row + r, target.col + c] = attr

                elif clause.action == Act.PLACE_AT:
                    offset = getattr(clause, '_offset', (0, 0))
                    dr, dc = offset
                    color = attr if attr is not None else target.color
                    for r in range(target.height):
                        for c in range(target.width):
                            if target.mask[r, c]:
                                nr = target.row + r + dr
                                nc = target.col + c + dc
                                if 0 <= nr < result.shape[0] and 0 <= nc < result.shape[1]:
                                    result[nr, nc] = color

                elif clause.action == Act.PLACE_PIXEL and attr is not None:
                    pos = getattr(clause, '_pixel_pos', None)
                    if pos is not None:
                        pr, pc = pos
                        if 0 <= pr < result.shape[0] and 0 <= pc < result.shape[1]:
                            result[pr, pc] = attr
                    else:
                        # Place at answer region bottom center
                        answer_regions = [r for r in facts.regions if r.role == "answer"]
                        if answer_regions:
                            ar = answer_regions[0]
                            result[ar.r1, ar.center_col] = attr

                elif clause.action == Act.REMOVE:
                    pass  # already bg, don't place

                elif clause.action == Act.KEEP:
                    for r in range(target.height):
                        for c in range(target.width):
                            if target.mask[r, c]:
                                result[target.row + r, target.col + c] = target.color

                elif clause.action == Act.STAMP:
                    # Copy target's mask at offset; target itself is preserved
                    offset = getattr(clause, '_offset', (0, 0))
                    dr, dc = offset
                    color = attr if attr is not None else target.color
                    for r in range(target.height):
                        for c in range(target.width):
                            if target.mask[r, c]:
                                nr = target.row + r + dr
                                nc = target.col + c + dc
                                if 0 <= nr < result.shape[0] and 0 <= nc < result.shape[1]:
                                    result[nr, nc] = color

                elif clause.action == Act.GRAVITY:
                    # Project target along axis to grid border
                    direction = getattr(clause, '_gravity_dir', 'down')
                    color = attr if attr is not None else target.color
                    rows_g, cols_g = result.shape
                    if direction == 'down':
                        dr = rows_g - (target.row + target.height)
                    elif direction == 'up':
                        dr = -target.row
                    elif direction == 'right':
                        dr = 0  # dr/dc swap below
                    elif direction == 'left':
                        dr = 0
                    else:
                        dr = 0
                    if direction in ('down', 'up'):
                        for r in range(target.height):
                            for c in range(target.width):
                                if target.mask[r, c]:
                                    nr = target.row + r + dr
                                    nc = target.col + c
                                    if 0 <= nr < rows_g and 0 <= nc < cols_g:
                                        result[nr, nc] = color
                    elif direction == 'right':
                        dc = cols_g - (target.col + target.width)
                        for r in range(target.height):
                            for c in range(target.width):
                                if target.mask[r, c]:
                                    nr = target.row + r
                                    nc = target.col + c + dc
                                    if 0 <= nr < rows_g and 0 <= nc < cols_g:
                                        result[nr, nc] = color
                    elif direction == 'left':
                        dc = -target.col
                        for r in range(target.height):
                            for c in range(target.width):
                                if target.mask[r, c]:
                                    nr = target.row + r
                                    nc = target.col + c + dc
                                    if 0 <= nr < rows_g and 0 <= nc < cols_g:
                                        result[nr, nc] = color

                elif clause.action == Act.SLIDE:
                    # Slide target along axis until hitting non-bg cell
                    direction = getattr(clause, '_gravity_dir', 'down')
                    # For slide, always keep target's own color
                    # (support is for direction only, not color derivation)
                    color = target.color
                    # Derived direction: compute from support position
                    if direction == 'toward_support':
                        support = clause.find_support(target, facts)
                        if support:
                            s = support[0]
                            dr = (s.center_row - target.center_row)
                            dc = (s.center_col - target.center_col)
                            if abs(dr) > abs(dc) * 2:
                                direction = 'down' if dr > 0 else 'up'
                            elif abs(dc) > abs(dr) * 2:
                                direction = 'right' if dc > 0 else 'left'
                            else:
                                # Diagonal
                                direction = ('down' if dr > 0 else 'up') + ('right' if dc > 0 else 'left')
                        else:
                            direction = 'down'
                    rows_g, cols_g = result.shape
                    # Find max displacement before hitting an occupied cell
                    shift = _compute_slide_offset(
                        target, direction, inp, bg, rows_g, cols_g)
                    if direction in ('down', 'up'):
                        for r in range(target.height):
                            for c in range(target.width):
                                if target.mask[r, c]:
                                    nr = target.row + r + shift
                                    nc = target.col + c
                                    if 0 <= nr < rows_g and 0 <= nc < cols_g:
                                        result[nr, nc] = color
                    elif direction in ('left', 'right'):
                        for r in range(target.height):
                            for c in range(target.width):
                                if target.mask[r, c]:
                                    nr = target.row + r
                                    nc = target.col + c + shift
                                    if 0 <= nr < rows_g and 0 <= nc < cols_g:
                                        result[nr, nc] = color
                    else:
                        # Diagonal: shift is number of steps
                        dr_sign = 1 if 'down' in direction else -1
                        dc_sign = 1 if 'right' in direction else -1
                        for r in range(target.height):
                            for c in range(target.width):
                                if target.mask[r, c]:
                                    nr = target.row + r + shift * dr_sign
                                    nc = target.col + c + shift * dc_sign
                                    if 0 <= nr < rows_g and 0 <= nc < cols_g:
                                        result[nr, nc] = color

                elif clause.action == Act.TRANSFORM:
                    # Geometric transform: apply to target's mask, place in-situ
                    transform = getattr(clause, '_transform', 'flip_h')
                    color = attr if attr is not None else target.color
                    mask = target.mask
                    if transform == 'flip_h':
                        mask = mask[:, ::-1]
                    elif transform == 'flip_v':
                        mask = mask[::-1, :]
                    elif transform == 'rot90':
                        mask = np.rot90(mask)
                    elif transform == 'rot180':
                        mask = np.rot90(mask, 2)
                    elif transform == 'transpose':
                        mask = mask.T
                    h, w = mask.shape
                    for r in range(h):
                        for c in range(w):
                            if mask[r, c]:
                                nr = target.row + r
                                nc = target.col + c
                                if 0 <= nr < result.shape[0] and 0 <= nc < result.shape[1]:
                                    result[nr, nc] = color

                elif clause.action == Act.FILL_INTERIOR:
                    # Fill bg holes within target's bbox
                    # Check result (not inp) so earlier clauses' fills aren't overwritten
                    color = attr if attr is not None else getattr(clause, '_fill_color', None)
                    if color is not None:
                        for r in range(target.height):
                            for c in range(target.width):
                                if not target.mask[r, c]:
                                    nr = target.row + r
                                    nc = target.col + c
                                    if 0 <= nr < result.shape[0] and 0 <= nc < result.shape[1]:
                                        if result[nr, nc] == bg:
                                            result[nr, nc] = color

        return result


# ---------------------------------------------------------------------------
# Helpers for grid-level actions
# ---------------------------------------------------------------------------

def _find_enclosed_bg(grid, bg):
    """Return boolean mask of bg cells not reachable from grid border."""
    from collections import deque
    rows, cols = grid.shape
    reachable = np.zeros((rows, cols), dtype=bool)
    q = deque()
    for r in range(rows):
        for c in range(cols):
            if (r == 0 or r == rows - 1 or c == 0 or c == cols - 1) and grid[r, c] == bg:
                reachable[r, c] = True
                q.append((r, c))
    while q:
        r, c = q.popleft()
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if 0 <= nr < rows and 0 <= nc < cols and not reachable[nr, nc] and grid[nr, nc] == bg:
                reachable[nr, nc] = True
                q.append((nr, nc))
    enclosed = (grid == bg) & ~reachable
    return enclosed if np.any(enclosed) else None


def _compute_slide_offset(target, direction, grid, bg, rows, cols):
    """Compute how far target can slide before hitting a non-bg cell or border.

    Scans the grid (not the result) for obstacles — this means objects that
    exist in the input act as walls.
    """
    # Build a set of cells occupied by OTHER objects (not the target itself)
    target_cells = set()
    for r in range(target.height):
        for c in range(target.width):
            if target.mask[r, c]:
                target_cells.add((target.row + r, target.col + c))

    if direction == 'down':
        max_shift = rows - (target.row + target.height)
        for d in range(1, max_shift + 1):
            for r in range(target.height):
                for c in range(target.width):
                    if target.mask[r, c]:
                        nr = target.row + r + d
                        nc = target.col + c
                        if nr >= rows:
                            return d - 1
                        if (nr, nc) not in target_cells and grid[nr, nc] != bg:
                            return d - 1
        return max_shift
    elif direction == 'up':
        max_shift = target.row
        for d in range(1, max_shift + 1):
            for r in range(target.height):
                for c in range(target.width):
                    if target.mask[r, c]:
                        nr = target.row + r - d
                        nc = target.col + c
                        if nr < 0:
                            return -(d - 1)
                        if (nr, nc) not in target_cells and grid[nr, nc] != bg:
                            return -(d - 1)
        return -max_shift
    elif direction == 'right':
        max_shift = cols - (target.col + target.width)
        for d in range(1, max_shift + 1):
            for r in range(target.height):
                for c in range(target.width):
                    if target.mask[r, c]:
                        nr = target.row + r
                        nc = target.col + c + d
                        if nc >= cols:
                            return d - 1
                        if (nr, nc) not in target_cells and grid[nr, nc] != bg:
                            return d - 1
        return max_shift
    elif direction == 'left':
        max_shift = target.col
        for d in range(1, max_shift + 1):
            for r in range(target.height):
                for c in range(target.width):
                    if target.mask[r, c]:
                        nr = target.row + r
                        nc = target.col + c - d
                        if nc < 0:
                            return -(d - 1)
                        if (nr, nc) not in target_cells and grid[nr, nc] != bg:
                            return -(d - 1)
        return -max_shift

    # Diagonal directions
    if 'down' in direction or 'up' in direction:
        dr_sign = 1 if 'down' in direction else -1
        dc_sign = 1 if 'right' in direction else -1
        max_shift = min(rows, cols)
        for d in range(1, max_shift + 1):
            for r in range(target.height):
                for c in range(target.width):
                    if target.mask[r, c]:
                        nr = target.row + r + d * dr_sign
                        nc = target.col + c + d * dc_sign
                        if nr < 0 or nr >= rows or nc < 0 or nc >= cols:
                            return d - 1
                        if (nr, nc) not in target_cells and grid[nr, nc] != bg:
                            return d - 1
        return max_shift

    return 0


def _compute_frame_colors(grid, bg):
    """Find enclosed bg regions and determine their frame color.

    Returns list of (region_mask, fill_color) pairs.
    Each enclosed bg connected component gets filled with the most common
    adjacent non-bg color (the "frame" color).
    """
    from collections import Counter, deque
    from scipy import ndimage

    rows, cols = grid.shape
    reachable = np.zeros((rows, cols), dtype=bool)
    q = deque()
    for r in range(rows):
        for c in range(cols):
            if (r == 0 or r == rows - 1 or c == 0 or c == cols - 1) and grid[r, c] == bg:
                reachable[r, c] = True
                q.append((r, c))
    while q:
        r, c = q.popleft()
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if 0 <= nr < rows and 0 <= nc < cols and not reachable[nr, nc] and grid[nr, nc] == bg:
                reachable[nr, nc] = True
                q.append((nr, nc))

    enclosed = (grid == bg) & ~reachable
    if not np.any(enclosed):
        return []

    labeled, n = ndimage.label(enclosed, structure=np.ones((3, 3)))
    struct4 = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]], dtype=bool)

    results = []
    for lid in range(1, n + 1):
        comp = labeled == lid
        dilated = ndimage.binary_dilation(comp, structure=struct4)
        border = dilated & ~comp
        vals = grid[border]
        non_bg = vals[vals != bg]
        if len(non_bg) > 0:
            color = int(Counter(non_bg.tolist()).most_common(1)[0][0])
            results.append((comp, color))

    return results


# ---------------------------------------------------------------------------
# Helpers for relational predicates
# ---------------------------------------------------------------------------

def _are_adjacent(a: ObjFact, b: ObjFact) -> bool:
    """Check if two objects are 4-adjacent (touching but not overlapping)."""
    # Vertical adjacency
    if (abs(a.row - (b.row + b.height)) <= 1 or abs(b.row - (a.row + a.height)) <= 1):
        if not (a.col + a.width <= b.col or b.col + b.width <= a.col):
            return True
    # Horizontal adjacency
    if (abs(a.col - (b.col + b.width)) <= 1 or abs(b.col - (a.col + a.width)) <= 1):
        if not (a.row + a.height <= b.row or b.row + b.height <= a.row):
            return True
    return False


def _is_contained(inner: ObjFact, outer: ObjFact) -> bool:
    """Check if inner's bbox is fully inside outer's bbox."""
    return (outer.row <= inner.row and
            outer.col <= inner.col and
            outer.row + outer.height >= inner.row + inner.height and
            outer.col + outer.width >= inner.col + inner.width and
            outer.size > inner.size)
