# Re-export: canonical location is aria.legacy.structural_edit
from aria.legacy.structural_edit import *  # noqa: F401,F403
from aria.legacy.structural_edit import (  # noqa: F401 — private names used by tests
    _DIRECTION_SIBLINGS,
    _GROUPING_SWAPS,
    _ObjectMatch,
    _ProgramRanker,
    _build_movement_programs_color_size,
    _composition_edits,
    _correspondence_movement_edits,
    _delta_edits,
    _direction_edits,
    _extract_foreground_objects,
    _find_consistent_color_deltas,
    _find_consistent_color_size_deltas,
    _generate_edits,
    _generate_semantic_edits,
    _generate_shallow_edits,
    _grouping_edits,
    _match_objects,
    _mutate_rule_grouping,
    _near_far_edits,
    _promotion_edits,
    _recolor_edits,
)
